### ISSUE TITLE
New coupled run with increased seasalt_emis_scale

### ISSUE THREAD

**Issue by adamrher** [NCAR/cesm_dev#20]
### Purpose of the run

To bring TOA radiation into balance

### Description of the run

Coupled run with increased seasalt_emis_scale = 1.0 -> 1.5, using a baseline of 116 (#19). 

@gustavo-marques wondering if you'd prefer the ocean configuration of 115 (#18) in new runs?

### Suffix in the casename

117

### Namelist modifications

seasalt_emis_scale = 1.5

### Source modifications

SourceMods

### Sandbox

cesm3_0_beta04

### Contact info

@adamrher @PeterHjortLauritzen @dlawrenncar 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
I have set `b.e30_beta04.BLT1850.ne30_t232_wgx3.117` based on `116` except:
```
seasalt_emis_scale = 1.0 -> 1.5
```
It is ready to start but I can add the ocean setting if Gustavo prefers that.

**Comment by cecilehannay** [comment]
@gustavo-marques 
If you decide you want to add the setting of 115 for the ocean, please confirm that all we need to add is:
```
MAXTRUNC = 1000
MIN_SALINITY = 1.e-06
USE_BODNER23 = True
CR = 0.03
MIN_WSTAR2 = 1.0E-09
BLD_DECAYING_TFILTER = 8.64E+04
MLD_DECAYING_TFILTER = 2.592E+06
BLD_GROWING_TFILTER = 300.
MLD_GROWING_TFILTER = 3600.
MLE_USE_PBL_MLD = True
```

ALso, there was a request from @wwieder to add in our future runs:
```
finidat = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/initdata_esmf/ctsm5.3/ctsm53n04ctsm52028_ne30pg3t232_BgcCrop_exice_pSASU.clm60.r.0121-01-01.nc'

reseed_dead_plants = .true.

! turn off shifting cultivation
do_grossunrep = .false.

! do this for isotopes
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
```
Do we want this in 117?

**Comment by gustavo-marques** [comment]
@cecilehannay @adamrher, we want to use the ocean configuration of 115 (https://github.com/NCAR/cesm_dev/issues/18). 
Cecile, this is what is needed in `user_nl_mom`:

```
MAXTRUNC = 1000

MLE_USE_PBL_MLD = True

MLE%
USE_BODNER23 = True
CR = 0.03
MIN_WSTAR2 = 1.0E-09
BLD_DECAYING_TFILTER = 8.64E+04
MLD_DECAYING_TFILTER = 2.592E+06
BLD_GROWING_TFILTER = 300.
MLD_GROWING_TFILTER = 3600.
%MLE
```

**Comment by cecilehannay** [comment]
Started as run #21
